language: generic 
sudo: required
services:
        - docker
before_install:
        - docker build -t rk90229/react-test-case -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true  rk90229/react-test-case npm test 
after_success:
        - docker build -t rk90229/multi-client  ./client
        - docker build -t rk90229/multi-nginx ./nginx
        - docker build -t rk90229/multi-server ./server
        - docker build -t rk90229/multi-worker ./worker
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push rk90229/multi-client
        - docker push rk90229/multi-nginx
        - docker push rk90229/multi-server
        - docker push rk90229/multi-worker

